### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by BillF1953**
I hope I'm not being too much of bother, but I wanted to follow up with you and add the Cygwin/Clion configuration in the code.  Have a great evening!

Tyler

### CODE REVIEW

**Comment by snikulov** [comment]
Thank you for contribution.

For what reason option ```-std=gnu++0x``` added?
AFAIR, new C++ standard doesn't required  for this example.
What problem are you trying to solve?

**Comment by BillF1953** [comment]
Hi, 

I get 3 compiler errors on cygwin using the default using c++11. 

${DIR}/include/gtest/internal/gtest-port.h:2346:51: error: 'fileno' was not declared in this scope
 inline int FileNo(FILE* file) { return fileno(file); }
${DIR}/include/gtest/internal/gtest-port.h:2352:57: error: 'strdup' was not declared in this scope
 inline char* StrDup(const char* src) { return strdup(src); }
${DIR}/include/gtest/internal/gtest-port.h:2380:71: error: 'fdopen' was not declared in this scope
 inline FILE* FDOpen(int fd, const char* mode) { return fdopen(fd, mode); }

Switching the compiler was a suggestion from the CLion Documentation: 

"In case you are using Cygwin, use the GNU dialect of the C++ language for your project:set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++0x")"
https://blog.jetbrains.com/clion/2015/10/new-clion-1-2-eap-build-brings-you-google-test/

The same error appeared on StackOverflow. One of the contributors mentioned that he thought these 3 uses violated the ANSI standards and therefore c++11 disabled them. 
GoogleTest 1.6 with Cygwin 1.7 compile error: 'fileno' was not declared in this scope

  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
GoogleTest 1.6 with Cygwin 1.7 compile error: 'fileno' was not decl...
 GoogleTest 1.6 with Cygwin 1.7: 'fileno' was not declared in this scope Error message when building a s...  |   |

  |

  |

 

Best Wishes, 

Tyler

 

    On Wednesday, August 31, 2016 3:21 AM, Sergei Nikulov <notifications@github.com> wrote:
 

 Thank you for contribution.For what reason option -std=gnu++0x added?
AFAIR, new C++ standard doesn't required for this example.
What problem are you trying to solve?—

**Comment by snikulov** [comment]
Ok.
But maybe it should be as follows
```
if(CYGWIN)
    add_definitions(-std=gnu++0x)
endif(CYGWIN)
```

**Comment by GogolsNose** [comment]
I really like that idea!

**Comment by snikulov** [comment]
Closed as outdated.

**Pull request closed without merging**
