### PR TITLE
use cmake threads find_package macro

### PR DESCRIPTION
**Pull request by ticapix**
great sample code. Minor proposal to use cmake macro for pthreads flags

### CODE REVIEW

**Comment by snikulov** [comment]
Hi,
Thank you for proposal.

It seems strange to me adding find_package(Threads REQUIRED) in CMAKE_COMPILER_IS_GNUCXX condition. 
And then use CMAKE_THREAD_LIBS_INIT when condition is MSVC.

Could you please describe more about problem you've tried to solve with this change?

**Comment by ticapix** [comment]
As I don't have access to a win32 platform to try out, I just replaced the manual configuration of pthread for gnu platform by the standard cmake macro.
I bet it's safe to move the `find_package(Threads REQUIRED)` macro outside of the if block.

**Comment by snikulov** [comment]
Could you please check develop branch?
Is it what you want to achieve?

**Comment by snikulov** [comment]
Changes merged as per #7
Thank you @ticapix for proposal.

**Pull request closed without merging**
